from enum import Enum


class CmdTypes(Enum):
    UPLOAD_DOCUMENTS = "UPLOAD_DOCUMENTS"
    PERSIST_TO_STORE = "PERSIST_TO_STORE"
    BULK_PERSIST_TO_STORE = "BULK_PERSIST_TO_STORE"
    BUILD_WORKFLOW = "BUILD_WORKFLOW"
